/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.felixsoinfotech.karma_gateway.client.friendship_service.api;

import com.felixsoinfotech.karma_gateway.client.friendship_service.model.RegisteredUser;
import com.felixsoinfotech.karma_gateway.client.friendship_service.model.RegisteredUserModel;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-02-07T16:27:56.038+05:30[Asia/Calcutta]")

@Api(value = "RegisteredUserGraphResource", description = "the RegisteredUserGraphResource API")
public interface RegisteredUserGraphResourceApi {

    @ApiOperation(value = "checkRegisteredUserIsFollowed", nickname = "checkRegisteredUserIsFollowedUsingGET", notes = "", response = Boolean.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Boolean.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/Is-Followed/{userId}/{wellWisherId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Boolean> checkRegisteredUserIsFollowedUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId,@ApiParam(value = "wellWisherId",required=true) @PathVariable("wellWisherId") String wellWisherId);


    @ApiOperation(value = "checkRegisteredUserIsFollowing", nickname = "checkRegisteredUserIsFollowingUsingGET", notes = "", response = Boolean.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Boolean.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/Is-Following/{userId}/{wellWishingId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Boolean> checkRegisteredUserIsFollowingUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId,@ApiParam(value = "wellWishingId",required=true) @PathVariable("wellWishingId") String wellWishingId);


    @ApiOperation(value = "checkRegisteredUsersAreFriends", nickname = "checkRegisteredUsersAreFriendsUsingGET", notes = "", response = Boolean.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Boolean.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/registeredUsers-AreFriends/{registeredUserOneUserId}/{registeredUserTwoUserId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Boolean> checkRegisteredUsersAreFriendsUsingGET(@ApiParam(value = "registeredUserOneUserId",required=true) @PathVariable("registeredUserOneUserId") String registeredUserOneUserId,@ApiParam(value = "registeredUserTwoUserId",required=true) @PathVariable("registeredUserTwoUserId") String registeredUserTwoUserId);


    @ApiOperation(value = "countOfWellWishersByUserId", nickname = "countOfWellWishersByUserIdUsingGET", notes = "", response = Long.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Long.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/wellWishers-count/{userId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Long> countOfWellWishersByUserIdUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId);


    @ApiOperation(value = "countOfWellWishingByUserId", nickname = "countOfWellWishingByUserIdUsingGET", notes = "", response = Long.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Long.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/wellWishing-count/{userId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Long> countOfWellWishingByUserIdUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId);


    @ApiOperation(value = "createWellWisherAndWellWishing", nickname = "createWellWisherAndWellWishingUsingPOST", notes = "", response = String.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/createWellWisher-wellWishing/registeredUser/",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<String> createWellWisherAndWellWishingUsingPOST(@ApiParam(value = "registeredUserModel" ,required=true )  @Valid @RequestBody RegisteredUserModel registeredUserModel);


    @ApiOperation(value = "findAllWellWishersByUserId", nickname = "findAllWellWishersByUserIdUsingGET", notes = "", response = RegisteredUser.class, responseContainer = "List", tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RegisteredUser.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/well-Wishers/{userId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<RegisteredUser>> findAllWellWishersByUserIdUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId);


    @ApiOperation(value = "findAllWellWishingByUserId", nickname = "findAllWellWishingByUserIdUsingGET", notes = "", response = RegisteredUser.class, responseContainer = "List", tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RegisteredUser.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/well-Wishing/{userId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<RegisteredUser>> findAllWellWishingByUserIdUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId);


    @ApiOperation(value = "getRegisteredUserIsExist", nickname = "getRegisteredUserIsExistUsingGET", notes = "", response = RegisteredUser.class, tags={ "registered-user-graph-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RegisteredUser.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/graph/registeredUser/is-exist/{userId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<RegisteredUser> getRegisteredUserIsExistUsingGET(@ApiParam(value = "userId",required=true) @PathVariable("userId") String userId);

}
